ini_open("option.ini");
//video_section
ini_write_real("video","full_screen",global.full_screen);
ini_write_real("video","vsync",global.vsync);
ini_write_real("video","scale",global.scale);
//audio_section
ini_write_real("audio","sound",global.sound);
ini_write_real("audio","music",global.music);
//controls_section
ini_write_real("controls","left",global.left);
ini_write_real("controls","right",global.right);
ini_write_real("controls","up",global.up);
ini_write_real("controls","down",global.down);
ini_write_real("controls","shoot",global.shoot);
ini_write_real("controls","jump",global.jump);
ini_write_real("controls","special",global.special);
ini_write_real("controls","enter",global.enter);
ini_close();
